### ISSUE TITLE
e-sparqlEndpoint: Adjust for Sesame 2.8

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/DPUs#101]
When I use this DPU, I get:
```
Expected '<' or '_', found: @ [line 1]

Stack trace:
org.openrdf.rio.RDFParseException Expected '<' or '_', found: @ [line 1]
   at org.openrdf.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:440)
   at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:704)
   at org.openrdf.rio.ntriples.NTriplesParser.reportFatalError(NTriplesParser.java:674)
   at org.openrdf.rio.ntriples.NTriplesParser.parseSubject(NTriplesParser.java:369)
   at org.openrdf.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:301)
   at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:192)
   at eu.unifiedviews.plugins.extractor.rdffromsparql.SPARQLExtractor.extractDataFromEnpointGraph(SPARQLExtractor.java:365)
   at eu.unifiedviews.plugins.extractor.rdffromsparql.SPARQLExtractor.extractFromSPARQLEndpoint(SPARQLExtractor.java:281)
   at eu.unifiedviews.plugins.extractor.rdffromsparql.RdfFromSparqlEndpoint.execute(RdfFromSparqlEndpoint.java:146)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
```

It is connected to the Sesame 2.8 update

**Comment by jakubklimek** [comment]
Fixed by @skodape
