### ISSUE TITLE
e-sparqlEndpoint doesn't send correct MIME type

### ISSUE THREAD

**Issue by jindrichmynarz** [mff-uk/DPUs#104]
Using e-sparqlEndpoint compiled from 71286036ff0a0089a6b77bb7d8827b1617b46f96 I found out that it fails with the [Parliament RDF store](http://parliament.semwebcentral.org/) (and presumably others) because it doesn't send correct MIME type (`application/x-www-form-urlencoded`, `application/sparql-query`, or `application/sparql-update`).

```
Execution failed because: Operation failed.eu.unifiedviews.dpu.DPUException: Operation failed.
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.checkFailState(FaultTolerance.java:241)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:299)
at cz.cuni.mff.xrg.uv.extractor.sparqlendpoint.SparqlEndpoint.innerExecute(SparqlEndpoint.java:78)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.openrdf.query.QueryEvaluationException: 

HTTP ERROR 415

Problem accessing /parliament/sparql. Reason:

    Request content type must be application/x-www-form-urlencoded, application/sparql-query, or application/sparql-update
Powered by Jetty://

at org.openrdf.repository.sparql.query.SPARQLGraphQuery.evaluate(SPARQLGraphQuery.java:56)
at cz.cuni.mff.xrg.uv.extractor.sparqlendpoint.SparqlEndpoint$2.action(SparqlEndpoint.java:84)
at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:296)
... 6 more
Caused by: org.openrdf.repository.RepositoryException: 

HTTP ERROR 415

Problem accessing /parliament/sparql. Reason:

    Request content type must be application/x-www-form-urlencoded, application/sparql-query, or application/sparql-update
Powered by Jetty://

at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:953)
at org.openrdf.http.client.HTTPClient.sendGraphQueryViaHttp(HTTPClient.java:847)
at org.openrdf.http.client.HTTPClient.getRDFBackground(HTTPClient.java:741)
at org.openrdf.http.client.HTTPClient.sendGraphQuery(HTTPClient.java:413)
at org.openrdf.repository.sparql.query.SPARQLGraphQuery.evaluate(SPARQLGraphQuery.java:50)
... 8 more
```

**Comment by skodape** [comment]
As this DPU was donated to the core repository, the issue shall be solved there.
